SQLALCHEMY_DATABASE_URI = 'sqlite:///db.sqlite3'
SQLALCHEMY_ECHO = True
SECRET_KEY = 'event-tool'
PAGINATION_ITEMS_PER_PAGE = 10
TIMEZONE = 'Europe/Zurich'
SIMPLEMDE_JS_IIFE = True
SIMPLEMDE_USE_CDN = True
